project:
  type: website
  output-dir: _site
  preview:
    port: 4000
    timeout: 1200

website:
  title: "Ford Johnson"
  site-url: https://tidytuesday.fordjohnson.dev
  open-graph: true
  search: false
  favicon: images/logo.png

  navbar:
    background: white
    right:
      - text: Portfolio
        href: https://fordjohnson.dev/

  page-footer:
    center:
      - icon: github
        href: https://github.com/bradfordjohnson
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson
  announcement: 
    icon: rocket-takeoff
    dismissable: true
    content: |
      Welcome! Explore my contributions to the TidyTuesday project and check out the code <a href="https://github.com/bradfordjohnson/tidytuesday/tree/main"> here</a>.
    type: primary
    position: below-navbar

format:
  html:
    include-in-header:
      - ga4/gtm_header.html
      - ga4/gtm_click_listener.html
    include-before-body: ga4/gtm_body.html
    anchor-sections: false
    theme: styles.scss
    toc: true
    canonical-url: true
