project:
  type: website
  output-dir: docs

website:
  title: "Ford Johnson"
  site-url: https://tidytuesday.fordjohnson.dev
  search: false
  navbar:
    right:    
      - text: About
        href: about/index.qmd
      - icon: github
        href: https://github.com/bradfordjohnson
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson
  page-footer:
    center:
      - icon: github
        href: https://github.com/bradfordjohnson
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson

format:
  html:
    anchor-sections: false
    theme: styles.scss
    toc: false
    canonical-url: true



